definitions:
  models.BookModel:
    properties:
      book_description:
        type: string
      book_name:
        type: string
      create_at:
        type: string
      creator_id:
        type: string
      id:
        type: string
      last_modified_at:
        type: string
    type: object
  models.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      last_modified_at:
        type: string
      name:
        type: string
    type: object
  responses.CreateBookResponse:
    properties:
      book_description:
        type: string
      book_name:
        type: string
      create_at:
        type: string
      creator_id:
        type: string
      id:
        type: string
      last_modified_at:
        type: string
    type: object
  responses.CreateCostResponse:
    properties:
      id:
        type: string
    type: object
  responses.CreateUserResponse:
    properties:
      id:
        type: string
    type: object
  utils.APIResponse:
    properties:
      data: {}
      message:
        type: string
      status:
        type: string
    type: object
  validators.CostPayerRequest:
    properties:
      amount:
        type: number
      user_id:
        type: string
    required:
    - amount
    - user_id
    type: object
  validators.CostSharerRequest:
    properties:
      share_amount:
        type: number
      user_id:
        type: string
    required:
    - share_amount
    - user_id
    type: object
  validators.CreateBookRequest:
    properties:
      book_description:
        type: string
      book_name:
        minLength: 1
        type: string
    required:
    - book_name
    type: object
  validators.CreateCostRequest:
    properties:
      amount:
        type: number
      book_id:
        type: string
      currency:
        type: string
      description:
        type: string
      payers:
        items:
          $ref: '#/definitions/validators.CostPayerRequest'
        type: array
      sharers:
        items:
          $ref: '#/definitions/validators.CostSharerRequest'
        type: array
    required:
    - amount
    - book_id
    - currency
    - payers
    - sharers
    type: object
  validators.CreateUserRequest:
    properties:
      email:
        type: string
      name:
        minLength: 1
        type: string
    required:
    - name
    type: object
  validators.GetBookByIDRequest:
    properties:
      bookID:
        type: string
    required:
    - bookID
    type: object
  validators.GetBookListRequest:
    properties:
      id:
        type: string
    required:
    - id
    type: object
  validators.JoinBookRequest:
    properties:
      book_id:
        type: string
    required:
    - book_id
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is the API of Bill Breaker
  title: Bill Breaker API
  version: "1.0"
paths:
  /api/v1/book:
    post:
      consumes:
      - application/json
      description: create new book with book info and user_id
      parameters:
      - description: User ID for authentication
        in: header
        name: X-User-ID
        required: true
        type: string
      - description: Create new book with info and user_id
        in: body
        name: book
        required: true
        schema:
          $ref: '#/definitions/validators.CreateBookRequest'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/utils.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/responses.CreateBookResponse'
              type: object
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/utils.APIResponse'
        "404":
          description: not found
          schema:
            $ref: '#/definitions/utils.APIResponse'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/utils.APIResponse'
      summary: Create new book
      tags:
      - books
  /api/v1/book/{book_id}:
    get:
      consumes:
      - application/json
      description: get book with book_id (and X-User-ID)
      parameters:
      - description: User ID for authentication
        in: header
        name: X-User-ID
        required: true
        type: string
      - description: Get book with book_id
        in: body
        name: book
        required: true
        schema:
          $ref: '#/definitions/validators.GetBookByIDRequest'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/utils.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/models.BookModel'
              type: object
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/utils.APIResponse'
        "404":
          description: not found
          schema:
            $ref: '#/definitions/utils.APIResponse'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/utils.APIResponse'
      summary: Get book by book_id
      tags:
      - books
  /api/v1/book/{book_id}/leave:
    delete:
      consumes:
      - application/json
      description: leave the book with book_id and user_id
      parameters:
      - description: User ID for authentication
        in: header
        name: X-User-ID
        required: true
        type: string
      - description: Leave the book with book_id
        in: path
        name: book_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/utils.APIResponse'
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/utils.APIResponse'
        "404":
          description: not found
          schema:
            $ref: '#/definitions/utils.APIResponse'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/utils.APIResponse'
      summary: Leave the book
      tags:
      - books
  /api/v1/book/cost:
    post:
      consumes:
      - application/json
      description: create new cost with cost information
      parameters:
      - description: User ID for authentication
        in: header
        name: X-User-ID
        required: true
        type: string
      - description: Create new cost with cost information
        in: body
        name: cost
        required: true
        schema:
          $ref: '#/definitions/validators.CreateCostRequest'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/utils.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/responses.CreateCostResponse'
              type: object
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/utils.APIResponse'
        "404":
          description: not found
          schema:
            $ref: '#/definitions/utils.APIResponse'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/utils.APIResponse'
      summary: Create new cost
      tags:
      - books
  /api/v1/book/join:
    post:
      consumes:
      - application/json
      description: join the book with book_id and user_id
      parameters:
      - description: User ID for authentication
        in: header
        name: X-User-ID
        required: true
        type: string
      - description: Join the book with book_id
        in: body
        name: book
        required: true
        schema:
          $ref: '#/definitions/validators.JoinBookRequest'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/utils.APIResponse'
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/utils.APIResponse'
        "404":
          description: not found
          schema:
            $ref: '#/definitions/utils.APIResponse'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/utils.APIResponse'
      summary: Join the book
      tags:
      - books
  /api/v1/book/list:
    get:
      consumes:
      - application/json
      description: get book list with user_id
      parameters:
      - description: User ID for authentication
        in: header
        name: X-User-ID
        required: true
        type: string
      - description: Get book list with user_id
        in: body
        name: book
        required: true
        schema:
          $ref: '#/definitions/validators.GetBookListRequest'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/utils.APIResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.BookModel'
                  type: array
              type: object
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/utils.APIResponse'
        "404":
          description: not found
          schema:
            $ref: '#/definitions/utils.APIResponse'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/utils.APIResponse'
      summary: Get book list
      tags:
      - books
  /api/v1/user:
    get:
      consumes:
      - application/json
      description: get user by id
      parameters:
      - description: User ID for authentication
        in: header
        name: X-User-ID
        required: true
        type: string
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/utils.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/models.User'
              type: object
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/utils.APIResponse'
        "404":
          description: not found
          schema:
            $ref: '#/definitions/utils.APIResponse'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/utils.APIResponse'
      summary: Get user
      tags:
      - users
    post:
      consumes:
      - application/json
      description: create new user with new device_id
      parameters:
      - description: Create new user by device_id
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/validators.CreateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/utils.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/responses.CreateUserResponse'
              type: object
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/utils.APIResponse'
        "404":
          description: not found
          schema:
            $ref: '#/definitions/utils.APIResponse'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/utils.APIResponse'
      summary: Create new user
      tags:
      - users
swagger: "2.0"
